test: implement type checking for typescript
shuvijs/redox pull request #25
Opened 2022-06-16 20:20 UTC by andy-yuanchang

2022-06-17 00:01 UTC, wangjinyang commented
react包里面的类型测试没改哦

2022-06-17 06:23 UTC, liximomo commented
原有的类型测试是不是可以删了？

2022-06-17 06:26 UTC, wangjinyang commented
类型提示是redox的一个很重要的功能，而且新开发的特性，也应该符合类型校验提示

2022-06-17 06:32 UTC, wangjinyang commented
> packages/redox/**tests**/ts-typings.test.ts 是不是可以删了？

可以啊

2022-06-20 08:41 UTC, liximomo requested changes
/lgtm

2022-06-20 08:41 UTC, liximomo approved these changes
/lgtm

2022-06-20 08:41 UTC, merged