Feat 0622 cache selector
shuvijs/redox pull request #29
Opened 2022-06-23 12:25 UTC by wangjinyang

2022-06-23 13:02 UTC, liximomo requested changes
/lgtm

2022-06-23 13:02 UTC, liximomo commented on packages/redox/package.json
> +  "types": "lib/index.d.ts",
types 是不是用 esm/index.d.ts 好一些

2022-06-23 13:02 UTC, liximomo commented on tsconfig.build.json
> +    "skipLibCheck": true,
这个文件的格式化很奇怪诶

2022-06-23 13:02 UTC, liximomo commented on packages/redox/tsconfig.build.json
> +	"compilerOptions": {
这个文件的格式化很奇怪诶

2022-06-23 13:24 UTC, wangjinyang commented on packages/redox/tsconfig.build.json
> +	"compilerOptions": {
https://github.com/shuvijs/redox/blob/825f429b938140569e2a8b358b15b616c59f23f1/tsconfig.build.json

很可能是网页显示的问题

2022-06-24 00:23 UTC, liximomo approved these changes
/lgtm

2022-06-24 00:23 UTC, merged