Feat 0808 views reactivity
shuvijs/redox pull request #36
Opened 2022-08-15 01:51 UTC by wangjinyang

2022-08-15 04:28 UTC, liximomo requested changes

2022-08-15 04:28 UTC, liximomo commented on packages/redox/src/core/views.ts
> +  if (views) {
前面已经判断不存在返回了，这里if多余了

2022-08-15 04:28 UTC, liximomo commented on packages/redox/src/core/views.ts
> +            return Object.assign({ $state: state }, state)
这里 直接 {$state: state} 貌似就可以了, Object.assign多余了

2022-08-15 04:28 UTC, liximomo commented on packages/redox/src/core/views.ts
> +                return Object.assign({ $state: state }, state)
Object.assign 多余了

2022-08-15 07:51 UTC, wangjinyang commented on packages/redox/src/core/views.ts
> +            return Object.assign({ $state: state }, state)
state: {
        a:{b:1},
	a1:1
      }

通过this.a访问a

old

reactive (()=>Object.assign({ $state: state }, state))

reactive对象上有a属性, 只会traked a， 关注a地址的变化

如果修改为：

reactive (()=>{ $state: state })

reactive对象上没有有a属性, 要先访问$state,再访问a

会traked $state，traked a， 关注$state和a地址的变化

结论： 此处不需要修改

2022-08-15 13:17 UTC, liximomo requested changes

2022-08-15 13:17 UTC, liximomo commented on packages/redox/src/core/views.ts
>    let viewRes = view(() => {
这有必要用view()?

2022-08-16 01:53 UTC, wangjinyang commented on packages/redox/src/core/views.ts
>    let viewRes = view(() => {
理论上和model的view是一样的额，可以缓存使用的view

2022-08-16 06:27 UTC, liximomo approved these changes
/lgtm

2022-08-16 06:27 UTC, merged