immer: base
shuvijs/redox pull request #42
Opened 2022-08-25 03:23 UTC by wangjinyang

2022-08-27 03:53 UTC, liximomo requested changes

2022-08-27 03:53 UTC, liximomo commented on packages/redox/src/reactivity/effect.ts
> +  for (const { record } of targetMap.values()) {
这个有必要?targetMap都被clear，它包含的值不也被清理了吗？

2022-08-27 03:53 UTC, liximomo commented on packages/redox/src/reactivity/effect.ts
> +    let parent = activeEffect!.targetMap.get(target)
这个 parent 名字起得不太合适吧

2022-08-27 03:53 UTC, liximomo commented on packages/redox/src/reactivity/effect.ts
> +      } else if (child.parent !== parent) {
```js
const a = {}

cosnt  state = {
  foo: 1,
  bar:  {
    zoo: 1.
  }
}
state.foo = a;
state.bar.zoo = a;
```

同一个对象可能有多个parent吧，这个目前是直接覆盖旧的parent？这样做不会有问题吗？

2022-08-27 03:53 UTC, liximomo commented on packages/redox/src/reactivity/effect.ts
> +    if (type === TriggerOpTypes.SET) {
set 和 get 分成两个函数单独处理吧，很多if条件只有set的时候才有意义，只是get的场景会做很多没必要的操作

2022-08-27 03:53 UTC, liximomo commented on packages/redox/src/reactivity/immer.ts
> +export class ProduceImpl<T extends {}> {
这个部分需要你讲解一下，期望你可以给我讲清楚这里的工作原理。

2022-08-27 03:58 UTC, liximomo requested changes

2022-08-27 03:58 UTC, liximomo commented on packages/redox/src/reactivity/immer.ts
> +import { warn } from '../warning'
不要起名为immer，这是个很糟糕的名字，改为producer

2022-08-27 04:02 UTC, liximomo requested changes

2022-08-27 04:02 UTC, liximomo commented on packages/redox/src/reactivity/immer.ts
> +      const draft = reactive(base)
为什么需要穿base，可以直接向view那样使用吗，提前准备好reactive， 例如

```js
let state = reactvie({ a: 1})

const viewA = view(() => state.a);

const newState = producer(() => {
  state.a = 1
})
```

2022-08-27 13:58 UTC, wangjinyang commented on packages/redox/src/reactivity/effect.ts
> +  for (const { record } of targetMap.values()) {
清除操作，这里面的只没有用了吧

2022-08-27 14:16 UTC, wangjinyang commented on packages/redox/src/reactivity/immer.ts
> +      const draft = reactive(base)
后面是要和view类似使用的，先要把immer的测试都过了

2022-08-29 02:58 UTC, wangjinyang commented on packages/redox/src/reactivity/effect.ts
> +      } else if (child.parent !== parent) {
state.foo.a =1

2022-08-29 03:01 UTC, wangjinyang commented on packages/redox/src/reactivity/effect.ts
> +      } else if (child.parent !== parent) {
state.bar.zoo.a.p=1

2022-09-08 04:04 UTC, liximomo requested changes

2022-09-08 04:04 UTC, liximomo commented on packages/redox/src/core/model.ts
> +        isReactive(this.state)
<img width="489" alt="image" src="https://user-images.githubusercontent.com/9816225/188368887-b00d5ec6-0907-4491-87a3-5a4d149dca88.png">
我们在_afterStateUpdate 里面不是已经把 this.state 转换为reactive了吗，这里为什么还要做这么多判断

2022-09-08 07:26 UTC, wangjinyang commented on packages/redox/src/core/model.ts
> +        isReactive(this.state)
当state数组的时候，isPlanObject(state) = false, reactive不会运行

2022-09-08 11:24 UTC, liximomo commented on packages/redox/src/core/model.ts
> +        isReactive(this.state)
那感觉要改得一起改？现在这样子的话，就是producer对数组生效，而 view 对数组不生效？

2022-09-08 12:25 UTC, wangjinyang commented on packages/redox/src/core/model.ts
> +        isReactive(this.state)
这个也是后面想优化的，if isObject(state) reactive(utils.shallowCopy(this._currentState))

2022-09-09 07:14 UTC, merged